### ISSUE TITLE
Problem with `addmod1_overflow3` test in `VMTests/vmArithmeticTest.json`

### ISSUE THREAD

**Issue by sorpaas** [ethereumproject/tests#3]
For this test, the actual code ran is `60056001600160000308600055`. It first pushes 0x05, 0x01, 0x01 and 0x00 on to the stack. Then ran `SUB` (0x03), which operates `0x00 - 0x01` which gives `0xFFF...FFF`. Then ran `ADDMOD` (0x08) using `0xFFF...FFF`, `0x01` and `0x05`. The last `600055` just store this value to storage at position `0x00`.

`((0x00 - 0x01) + 0x01) mod 0x05` should equal to `0x00`. However, the test states that the storage at `0x00` afterwards is `0x01`. Is the test wrong or am I missing something here?

**Comment by sorpaas** [comment]
Ping @sjmackenzie

**Comment by sjmackenzie** [comment]
Honestly, I cannot verify that those tests are accurate. This is a reason why I started the capnp testing strategy,

**Comment by sorpaas** [comment]
Fixed via https://github.com/ethereumproject/sputnikvm/pull/48
